id: P7877A255
initial_creation_type: input
source_metadata:
  Title: Prajñopāyaviniścayasiddhiḥ
  Editor: B Bhattacharyya
  Publisher: Oriental Institute
  Place of Publication: Baroda
  Year: '1929'
  प्रज्ञोपायविनिश्चयसिद्धिः:
    Text Version: Devanagari
    Input Personnel: Anjana Shakya
    Input Date: '2018'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Buddhist Studies
    Sponsor: University of the West
created_at: '2022-03-08T17:10:59.277011'
last_modified_at: '2022-03-08T17:10:59.277021'
